export { Background } from './background'
export { ChooseBox } from './chooseBox'
export { FigureImage } from './figureImage'
export { Intro } from './intro'
export { BackLog } from './backlog'
export { Load } from './load'
export { Setting } from './setting'
export { Pixi } from './pixiContainer'