name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - run: npm install yarn -g && yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - run: npm install yarn -g && yarn install

      - name: Build parser
        run: yarn parser:build

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: E2E
        run: yarn test:e2e
